### PR TITLE
Update libreoffice-still appcast and homepage

### PR DESCRIPTION
**Pull request by miccal**
Changes to match version in main repo.

### CODE REVIEW

**Comment by miccal** [comment]
@vitorgalvao the name "Still" is not really used by LibreOffice any more, but I am not sure what best to call this version -- "Stable" maybe?

**Comment by vitorgalvao** [comment]
Remind me the point of this version, seeing we have `libreoffice`.

**Comment by miccal** [comment]
Screen Shot 2020-02-29 at 09 38 59

**Comment by vitorgalvao** [comment]
Let’s keep it at `still` for now, but I think we should eventually get rid of this cask. The number don’t support its existence in the main repo:

```
libreoffice (added 2303 days ago)
30 days: 2,750 (#46)
90 days: 7,226 (#52)
365 days: 35,185 (#41)

libreoffice-still (added 1120 days ago)
30 days: 15 (#2278)
90 days: 49 (#2095)
365 days: 138 (#2211)
```

**Pull request merged**
