### PR TITLE
Update: temurin17.0.4.1 to 17.0.5

### PR DESCRIPTION
**Pull request by zdtsw**
NOT READY FOR REVIEW STILL WAITING FOR INTERNAL TESTS
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Review by miccal — APPROVED** [review]

**Comment by bpoland** [comment]
@miccal @zdtsw this broke things and results in a 404, can it be reverted?

**Comment by zdtsw** [comment]
> @miccal @zdtsw this broke things and results in a 404, can it be reverted?

i think jdk17 is not ready yet, for aarch64. it is only shipped for x64. 
sorry did not know it got merged already

**Comment by zdtsw** [comment]
@bpoland could you check it again if it still not working for jdk17? I just shipped out aarch64 macos

**Comment by bpoland** [comment]
> @bpoland could you check it again if it still not working for jdk17? I just shipped out aarch64 macos

Ah yes it's fixed now, thank you!

**Pull request merged**
