### PR TITLE
Update google-chrome-canary from 92.0.4507.0 to 92.0.4509.0

### PR DESCRIPTION
**Pull request by Logicer16**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by carlocab — DISMISSED** [review]
Thanks, @Logicer16.

**Comment by carlocab** [comment]
CI's stuck for some reason. Let's try to get it started again...

**Comment by Logicer16** [comment]
I think GitHub Actions went down.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
> I think GitHub Actions went down.

Oh yea, I forgot about the incident report.

**Comment by Logicer16** [comment]
Newer version came out whilst waiting. Do we want to close this and make a new pr or should I just commit the new version number to the branch.

**Comment by carlocab** [comment]
You can just amend your existing commit with the new version. Or you can open a new one with `bump-cask-pr` if that's simpler.

**Review by cho-m — APPROVED** [review]

**Pull request merged**
