### PR TITLE
Update zulu8 from 8.0.302,8.56.0.21-ca to 8.0.302,8.56.0.21-ca-fx

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
`brew livecheck zulu8` is returning a different version on CI to locally.

**Comment by cho-m** [comment]
I saw this before where running livecheck back-to-back jumps between the `-ca` and `-ca-fx` variants. This is probably a livecheck issue.

**Comment by bevanjkay** [comment]
@cho-m Should we always be updating to the `fx` version? Or should the cask jump between?

**Comment by cho-m** [comment]
We should probably stick to one variant. All `zulu` casks are currently using Non-JavaFX variant, so it is probably better to standardize on that one.

This is the version that is selected by default on https://www.azul.com/downloads/ (**Java Package** = `JDK`)

The FX variant is accessed by changing the **Java Package** drop-down to `JDK FX`.

**Pull request closed without merging**
