### PR TITLE
Add Temurin JDK 19

### PR DESCRIPTION
**Pull request by recursiveribbons**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by recursiveribbons** [comment]
While running `brew audit --new-cask temurin19`, I received the error that the GitHub repository is not notable enough, but the main download of this is at adoptium.net, and it is a JDK distribution, so I believe it still passes as notable.

**Comment by recursiveribbons** [comment]
As a JDK, there appears to be no files left over. This is also confirmed by the developers. Therefore, no `zap` block is required.

**Comment by recursiveribbons** [comment]
The livecheck is copied from temurin17

**Comment by razvanazamfirei** [comment]
Hi @recursiveribbons! Thank you for your contribution! Made some small changes, but this looks great! 👍

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
