### PR TITLE
Add dotnet-sdk2

### PR DESCRIPTION
**Pull request by bomehlsen**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].
- [x] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-versions/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

### CODE REVIEW

**Comment by bomehlsen** [comment]
If this gets approved, should I also update
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dotnet-sdk.rb
& 
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dotnet.rb
That is add this cask to `conflicts_with` in both?

**Comment by vitorgalvao** [comment]
From [acceptable casks](https://github.com/Homebrew/homebrew-cask-versions#acceptable-casks):

> Casks submitted here should be expected to be used by a reasonable number of people and supported by contributors long-term.

Why is this version being submitted? When would you use this instead of the latest stable?

**Comment by dahlia** [comment]
> Why is this version being submitted? When would you use this instead of the latest stable?

Although I'm not the author of this patch, it's because .NET Core *SDKs* are not incompatible between major versions; for example, .NET Core 3.0 SDK cannot build a project targeted to `netcoreapp22` (.NET Core 2.2).

**Comment by dahlia** [comment]
Anyways, it turns out I believe <https://github.com/isen-ng/homebrew-dotnet-sdk-versions> is better solution to use older .NET Core SDK versions.  Note that .NET Core SDK (i.e., `dotnet` command) in itself support multiple installations of more than one version (see `dotnet --list-sdks`), <https://github.com/isen-ng/homebrew-dotnet-sdk-versions> works well with that.  (On the other hand, this cask conflicts with `dotnet-sdk`, which means you can't install `dotnet-sdk` and `dotnet-sdk2` at a time.)

**Comment by bomehlsen** [comment]
Sorry, I completely forgot about this. I also started using https://github.com/isen-ng/homebrew-dotnet-sdk-versions as @dahlia suggests. I will close.

**Pull request closed without merging**
