### PR TITLE
Master

### PR DESCRIPTION
**Pull request by alex-ioma**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@alex-ioma I am also seeing that line in AppCleaner for `whatsapp-alpha` - what is the reasoning for removing it?

**Comment by alex-ioma** [comment]
@bevanjkay given the name of the Group Container being `com.facebook...`, I was afraid that this space might be shared among other apps, e.g. FB Messenger or might have not being created by WhatsApp and it was a misreading from AppCleaner. 

I was 50/50 if this needs removing  but had no time to check further so I created the PR. 

If you believe that it is safe to leave it, pls cancel the PR.

**Comment by bevanjkay** [comment]
@alex-ioma We do try to avoid it wherever possible but the documentation for `zap` does reference the fact that some shared files may be removed.

**Comment by alex-ioma** [comment]
Alright then, thanks!

**Pull request closed without merging**
