### PR TITLE
alfred-earlyaccess: rename to alfred5

### PR DESCRIPTION
**Pull request by bevanjkay**

### CODE REVIEW

**Comment by bevanjkay** [comment]
@unitof Sorry if you have to uninstall / reinstall this because of the change.

**Review by carlocab — APPROVED** [review]
Thanks!

**Comment by unitof** [comment]
All's good!

So following this paradigm, should `1password-beta` maybe rename to `1password8`?

Beta releases for 1Password 7 are still occasionally released.

**Comment by carlocab** [comment]
I'm less keen on renaming casks that have been around for a while, since they tend to break things for users. This one isn't too bad since I don't imagine there have been too many installs yet.

**Comment by bevanjkay** [comment]
@unitof It's a bit tricky to nail down an exact science, because the release schedules differ greatly between developers.

In this case I do think @carlocab's suggestion will work well because, we already have versioned casks for Alfred and this cask will only exist until version 5 is the stable branch (then we will add alfred4 here instead).

In the instance of `1password` it really depends if the beta/early access program is pinned to a specific version. Because this Alfred early access program will only exist until version 5 is released, and then there will be some time before it may or may not be opened again for the release of version 6.

**Comment by unitof** [comment]
Completely understand there are tons of factors here, and many I don't know. Still, I'm advocating for consistency between these two programs I have experience with.

I can confirm the cask currently named `1password-beta` extremely similar to this: an early access program that will end once 1Password 8 graduates to stable.

Realize it may be to much of a hassle to rename `1password-beta` at this point, but I think this pattern (early access to a next major version) has become fairly common for software with large beta tester communities, so I think it would be helpful to add it as a token naming convention—is that something I could help write and propose?

**Comment by carlocab** [comment]
Help with documentation is always welcome. I think we do have some existing guidelines about naming conventions, however.

**Pull request merged**
