### PR TITLE
Update julia-lts from 1.0.5 to 1.6.4

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Comment by pthariensflame** [comment]
I don't understand why this keeps failing.

**Comment by carlocab** [comment]
Neither do I. Ideas, @Homebrew/cask?

**Comment by carlocab** [comment]
Ah, I think I know why. GitHub runners have the Julia cask pre-installed. We should probably handle that here: https://github.com/Homebrew/homebrew-cask-versions/blob/d142f001d03a6477f0c753913e8cdca79689bc4c/.github/workflows/ci.yml#L58

**Comment by bevanjkay** [comment]
We can rebase this once https://github.com/Homebrew/homebrew-cask/pull/115361 is merged and migrated to the `homebrew-cask-*` repos.

**Comment by bevanjkay** [comment]
Thank you @pthariensflame

**Pull request merged**
