### PR TITLE
greenery-beta 0.9.4 (new Binary App Cask)

### PR DESCRIPTION
**Pull request by tmrdev**
This is the intial submission of the Greenery Beta release, v0.9.4. This is a Binary App release only for the Beta Cask, there is no associated source code for this app.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@tmrdev Casks in `homebrew-cask-versions` should have corresponding stable release in `homebrew-cask`. If there is no stable version of the cask then generally the `beta` is considered to be the most stable version.

**Comment by tmrdev** [comment]
> @tmrdev Casks in `homebrew-cask-versions` should have corresponding stable release in `homebrew-cask`. If there is no stable version of the cask then generally the `beta` is considered to be the most stable version.

At the present time this greenery-beta release at v0.9.4 is the most stable version of the app.  So we are submitting to homebrew-cask-versions while in beta and will submit to homebrew-cask once Greenery reaches v1.0.0

Also I'm seeing in the tests being run that there is a Notability issue with not enough Watchers, Forks, Stars, etc...

This is a Binary App Release for the greenery-beta Cask, with no associated source code, and it is my understanding that these Notability requirements are waived in this instance.

**Comment by bevanjkay** [comment]
@tmrdev In that case this should go in `homebrew-cask` as `greenery`.

**Comment by tmrdev** [comment]
> @tmrdev In that case this should go in `homebrew-cask` as `greenery`.

So if there is only one version of the app (for example there is not a beta and a stable version), then I should post to homebrew-cask as greenery?

**Comment by bevanjkay** [comment]
@tmrdev Yeah that's right, see the note here - https://docs.brew.sh/Acceptable-Casks#stable-versions


> But there is no Stable version!
> 
> When software is only available as a beta, development, or unstable version, its cask can go in the main homebrew/cask repository. When stable versions become available, only those will be accepted as subsequent updates.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/161104

**Pull request closed without merging**
