### PR TITLE
Update digikam-beta to 5.9.0-01

### PR DESCRIPTION
**Pull request by yurikoles**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Why the downgrade?

**Comment by yurikoles** [comment]
It seems that they switched to standard KDE scheme for pre-releases. 5.90.* means pre-6.

**Comment by yurikoles** [comment]
@reitermarkus bump?

**Comment by vitorgalvao** [comment]
Both the website and and appcast show 6.0 versions.

**Comment by yurikoles** [comment]
@vitorgalvao I took link here https://www.digikam.org/download/

**Pull request closed without merging**
