### PR TITLE
Add Legacy version (2.1.8) of Mixxx as "mixxx2.1"

### PR DESCRIPTION
**Pull request by araigumaG**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version). (Legacy but minor update applied)

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-versions/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by araigumaG** [comment]
It suppose to fail due to force push (´；ω；｀)

**Comment by araigumaG** [comment]
I re-pushed the branch without -f.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask-versions#acceptable-casks:

> Refuse legacy versions of gratis or open-source software, unless there is a clear demonstrable need for them.

What’s the clear demonstrable need for having a version `0.1` behind the one in the main repo?

**Comment by araigumaG** [comment]
As I wrote in commit message of 2d2e92a , Mixxx 2.2.0 have not been stable for users of macOS (including me) yet. The last stable version of Mixxx behind 2.2.0 is 2.1.5, not 2.1.6 or later. In other words, Mixxx developers have released 2.1.x (x∈[6,8]) forks as "Previous Stable" like LTS version, apart from their "Stable" build, since December 2018. Mixxx devs recommend that users on macOS should 2.1.x maintenance build instead of 2.2.0(, un"stable" build on macOS), so I suppose that 2.1.x is necessary. No one want reboot the software while her/his DJ performance, I think. At least I want never to do so.
 
Thanks for your reading.

**Comment by vitorgalvao** [comment]
> Mixxx devs recommend that users on macOS should 2.1.x maintenance build instead of 2.2.0(, un"stable" build on macOS)

Then downgrade the one in the main repo, which is for stable builds, with a link pointing to that.

**Pull request closed without merging**
