### PR TITLE
Add GOG Galaxy 2.0 beta

### PR DESCRIPTION
**Pull request by CoolTomatos**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-versions/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Doesn’t this `auto_update` as well?

It will need a `conflicts_with`.

**Comment by yurikoles** [comment]
@CoolTomatos 
Знімок екрана 2019-08-19 о 14 31 14

**Comment by CoolTomatos** [comment]
@yurikoles 
image
That's what I got whenever I click either one of the two `GalaxyUpdater`

**Comment by yurikoles** [comment]
@CoolTomatos you don't have to launch it manually, it's just a helper utility.

Nevertheless, it seems to be an invite-only:
Знімок екрана 2019-08-19 о 14 33 23

**Comment by vitorgalvao** [comment]
> Nevertheless, it seems to be an invite-only

In that case, there will be too few users. Let’s wait. Thank you for checking, @yurikoles.

**Comment by CoolTomatos** [comment]
@vitorgalvao @yurikoles yes at the moment it is invite only. sorry for getting too hyped about it :p

**Pull request closed without merging**
