### PR TITLE
feat(adguard-vpn): add new cask

### PR DESCRIPTION
**Pull request by dalisoft**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by dalisoft** [comment]
But there’s really Beta

> Why is there "Beta" in the name of AdGuard VPN?

> AdGuard VPN is currently under active development, and 'Beta' tag indicates just that. We're constantly rolling out updates to make it better, and to be as effective as possible, we need user feedback. Feel free to contact us with bug reports and feature requests at support@adguard.com.

This quote was copied from official website on bottom FAQ section

**Comment by carlocab** [comment]
Ok, that's fine. You should still submit this to the main repo.

**Comment by miccal** [comment]
@dalisoft [this is a documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version) so please submit this to the main `homebrew-cask` repository, thanks.

**Comment by dalisoft** [comment]
@miccal I created PR, https://github.com/Homebrew/homebrew-cask/pull/110734

**Pull request closed without merging**
