### PR TITLE
Add Yubico Authenticator Beta

### PR DESCRIPTION
**Pull request by joshka**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by joshka** [comment]
Note: https://github.com/Homebrew/homebrew-cask-drivers/blob/master/Casks/yubico-authenticator.rb has some an uninstall and zap stanza. Checking the installation after running the beta version (concurrently with the stable version) it seems none of the listed files are actually created. Hence I have not added them here.

**Review by miccal — APPROVED** [review]

**Comment by miccal** [comment]
Thank you @joshka.

**Comment by joshka** [comment]
@miccal as an aside, I have both the beta and stable version of this installed - there's no conflict per say other than the name of the application. I see you settled on the rename - is this the normal way, or does `-versions` tend to go with the conflicts approach?

**Comment by miccal** [comment]
We would usually go with the `conflicts_with` approach, but it a a little flaky between the `drivers` and `versions` repositories, so I went with your original approach.

**Pull request merged**
