### PR TITLE
libreoffice-still 7.5.8

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
The `livecheck` `url` https://www.libreoffice.org/download/release-notes/ is very out-of-date, and I cannot find a suitable alternative.

**Comment by miccal** [comment]
@samford the `livecheck` used in the main `libreoffice` Cask is:
```
  livecheck do
    url "https://download.documentfoundation.org/libreoffice/stable/"
    regex(%r{href="(\d+(?:\.\d+)+)/"}i)
  end
```
Perhaps we can use that same `url` here, but with the `livecheck` reporting the second-highest version?
```
|-> curl https://download.documentfoundation.org/libreoffice/stable/
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>Index of /libreoffice/stable</title>
  <link rel="stylesheet" href="/mirrorbrain.css" type="text/css" />
 </head>
 <body>
<h1>Index of /libreoffice/stable</h1>
<table><tr><th>&nbsp;</th><th><a href="?C=N;O=D">Name</a></th><th><a href="?C=M;O=A">Last modified</a></th><th><a href="?C=S;O=A">Size</a></th><th>Metadata</th></tr><tr><th colspan="5"><hr /></th></tr>
<tr><td valign="top">&nbsp;</td><td><a href="/libreoffice/">Parent Directory</a></td><td>&nbsp;</td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top">&nbsp;</td><td><a href="7.5.7/">7.5.7/</a></td><td align="right">26-Sep-2023 08:58  </td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top">&nbsp;</td><td><a href="7.5.8/">7.5.8/</a></td><td align="right">02-Nov-2023 12:58  </td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top">&nbsp;</td><td><a href="7.6.2/">7.6.2/</a></td><td align="right">26-Sep-2023 08:59  </td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><th colspan="5"><hr /></th></tr>
</table>
<address>Apache Server at <a href="mailto:hostmaster@documentfoundation.org">download.documentfoundation.org</a> Port 80</address>
<br/><address><a href="http://mirrorbrain.org/">MirrorBrain</a> powered by <a href="http://httpd.apache.org/">Apache</a></address>
</body></html>
```

**Comment by samford** [comment]
> Perhaps we can use that same `url` here, but with the `livecheck` reporting the second-highest version?

Yep, the latest "still" release is 7.5.8 and that's available on that page (they're the same versions as the main [download page](https://www.libreoffice.org/download/download-libreoffice/)), so that will work 👍

One moment and I'll push an updated `livecheck` block.

**Comment by miccal** [comment]
Thank you as always @samford.

**Review by samford — APPROVED** [review]

**Pull request merged**
