### PR TITLE
Update discord-development from 0.0.8762 to 0.0.8763

### PR DESCRIPTION
**Pull request by Adrthegamedev**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by Adrthegamedev** [comment]
Note that, while livecheck doesn't get this version, this version does exist on the server, so I would say it's fine to send ahead.

**Comment by bevanjkay** [comment]
@Adrthegamedev We always distribute the same version that you would receive if you went directly upstream. So we will need to wait until the livecheck matches the new version.

**Comment by Adrthegamedev** [comment]
ah ok 👍

**Comment by p-linnane** [comment]
This version is being returned by `livecheck` now, albeit with a different hash than was added to the cask. I've pushed an update to fix it. Just another reason why it's important for us to wait til it's actually live 😄

**Review by p-linnane — APPROVED** [review]

**Pull request closed without merging**
