### PR TITLE
Add 1Password 8 Early Access beta channel

### PR DESCRIPTION
**Pull request by unitof**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by unitof** [comment]
I _think_ this is the best name, as it is more futureproof than `1password8`. Additionally, the `.app` no longer includes the major version number.

**Comment by bevanjkay** [comment]
@unitof How does this differ from the existing `1password-beta` cask?
https://github.com/Homebrew/homebrew-cask-versions/blob/HEAD/Casks/1password-beta.rb

**Comment by unitof** [comment]
1Password 7, the current stable major version, has its own beta channel and current beta version.

1Password 8 is a "technical preview" of a forthcoming major rewrite, with its own `nightly` and `beta` channels.

Since development on 1Password 7 (including betas) will likely continue a few weeks/months before 1Password 8 is released, I thought `beta` should stay at 7.

There's also the issue that the 7 Beta will **not** auto-update to 8, even though the formula implies it will. That could be confusing to folks who have the `1password-beta` cask installed now that it's been bumped to 8.

Would it make sense to remove `:auto-updates true` from the now-updated `1password-beta` formula?

**Comment by unitof** [comment]
Which also makes the `zap` a bit difficult, since many of the app artifacts and identifiers have changed between 7 & 8, and it's not always clear which version(s) someone running `brew remove --zap 1password-beta` actually wants to zap.

**Comment by bevanjkay** [comment]
@unitof regarding the zap stanza, it is stored at the time of install. So when running `brew uninstall --zap 1password-beta` it will use the zap stanza that was present when the current version of the cask was installed.

**Comment by unitof** [comment]
Oh neato! Didn't know that.

Any thoughts on removing `auto-update`, since that's not true from 1Password 7 Beta -> 1Password 8 Beta?

**Pull request closed without merging**
