### PR TITLE
Update osu-development from 2020.820.0 to 2020.903.0

### PR DESCRIPTION
**Pull request by i0ntempest**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by miccal** [comment]
The `osu` cask in the main repo [was removed](https://github.com/Homebrew/homebrew-cask/pull/72262), so please remove the line:
```
conflicts_with cask: "osu"
```

**Comment by i0ntempest** [comment]
Done

**Review by reitermarkus — APPROVED** [review]

**Comment by claui** [comment]
@reitermarkus I agree. The current token no longer makes sense.

**Comment by i0ntempest** [comment]
For macOS this development version is the only version that runs (aside from the wine version that got removed), but for Windows we have another stable release version. So "osu-development" does make sense, but I do agree that this can be moved to the main repo.

**Comment by claui** [comment]
@i0ntempest What the README tells me:

> This project is under heavy development, but is in a stable state. Users are encouraged to try it out and keep it installed alongside the stable osu! client. It will continue to evolve to the point of eventually replacing the existing stable client as an update.

It says it’s essentially a stable version. The message that comes across to me is that it’s as stable a channel as it gets for macOS.
Mac users shouldn’t really have to concern themselves with osu’s Windows release channels, or how stable these are.

I’m not really familiar with osu so can you help clear this up? In what ways do you feel it’d be useful to keep the `-development` part?

**Comment by i0ntempest** [comment]
@claui This version (so called lazer version) is very different from the stable ver (totally different engine, UI, underlying behavior etc.), and it gets an update every a few days. If we remove ‘-development’ users may think this is the current stable version. However the devs do plan on releasing version as stable after most of the developments are done, so before that, I think we should either keep ‘-development’ or just rename it to ‘osu-lazer’.

**Comment by core-code** [comment]
> If we remove ‘-development’ users may think this is the current stable version

agreed - we shouldn't override upstreams decision in this case and possibly confuse users with that

**Comment by claui** [comment]
Good points @i0ntempest and @core-code. Convinced 👍

**Comment by i0ntempest** [comment]
So should I close this and move this cask to the main repo?

**Comment by vitorgalvao** [comment]
> So should I close this and move this cask to the main repo?

I think the consensus is to keep it in this repo.

Also, I would not be opposed to readding the stable cask to the main repo, as long as we can get official links (homepage and url) that are not from a forum.

**Comment by i0ntempest** [comment]
The stable version is technically Windows only, the "macOS ver" is basically a wineskin wrapper so there's no official link.

**Pull request closed without merging**
