### PR TITLE
Add DB Browser for SQLite nightly

### PR DESCRIPTION
**Pull request by lucydodo**
After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask-versions/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by miccal** [comment]
@vitorgalvao thoughts on using `target:` instead of `conflicts_with cask:`?

**Comment by lucydodo** [comment]
First of all, I would like to say thank you to the @homebrew team.

To help with the review, I'll explain why I used `target:` instead of `conflict_with cask:`.
When I configure this Cask, I tried to use `conflict_with cask:`, but there are users who use the nightly build along with the stable version as needed. Above all, we do not distinguish whether it is a nightly build by name or icon,
so I thought change the name of the app by Cask so that the users can distinguish it is better.

**Comment by vitorgalvao** [comment]
> Above all, we do not distinguish whether it is a nightly build by name or icon,
> so I thought change the name of the app by Cask so that the users can distinguish it is better.

That’s understandable, but also not something we get into. Some upstream developers name their nightlies and betas clearly, others do not. We want to replicate whatever that is, not impose our naming conventions on users.

That’s why [`target:` as specific rules](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/app.md#target-should-only-be-used-in-select-cases). Either upstream needs to change the name of their app or this needs a `conflicts_with` (or we need to discuss our rule in that regard and reapply it to everything).

For this PR, `conflicts_with` is what needs to happen.

**Review by vitorgalvao — APPROVED** [review]

**Comment by lucydodo** [comment]
@vitorgalvao Oh, I didn't understand the document properly. I modified it according to the review. Sorry to bother you. 😞

**Comment by vitorgalvao** [comment]
> Sorry to bother you. 😞

No bother! Thank you for the fast fix.

**Pull request merged**
