### PR TITLE
Update psi-plus to 1.4.567-macOS10.12

### PR DESCRIPTION
**Pull request by tehnick**
After making all changes to the cask:
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution, but I’ll instead remove the cask. Analytics:

```
psi-plus (added 735 days ago)
30 days: 3 (#3474)
90 days: 9 (#3600)
365 days: 23 (#3237)
```

**Comment by tehnick** [comment]
Sorry, but I don't understand your comment with analytics. Could you describe your decision in more details?

Our previous maintainer in Psi+ project was inactive during [long time](https://sourceforge.net/projects/psiplus/files/macOS/pztrn/). Now I stepped in and become to prepare [builds](https://sourceforge.net/projects/psiplus/files/macOS/tehnick/) for macOS myself. I have automated this process and am going to build macOS app bundles for next Psi+ releases on regular basis...

A side note: I saw that sha256sum of my file uploaded to SF had been changed and this is very suspicious. Do you know why such change may happen?

**Comment by vitorgalvao** [comment]
> Sorry, but I don't understand your comment with analytics. Could you describe your decision in more details?

From [acceptable casks](https://github.com/Homebrew/homebrew-cask-versions#acceptable-casks):

> Casks submitted here should be expected to be used by a reasonable number of people

> I saw that sha256sum of my file uploaded to SF had been changed and this is very suspicious. Do you know why such change may happen?

https://en.wikipedia.org/wiki/SourceForge#Project_hijackings_and_bundled_malware

**Comment by tehnick** [comment]
I see. Thanks for info.

**Pull request closed without merging**
