### PR TITLE
vscodium-insiders: update depends_on and zap

### PR DESCRIPTION
**Pull request by toobuntu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by toobuntu** [comment]
The vscodium bundle identifier changed in 1.71.0 (Sep 2, 2022) to `com.vscodium` instead of `com.visualstudio.code.oss`. The current vscodium release is 1.85.1 (Dec 13, 2023).

I updated the zap accordingly. There were some zap entries listed in the existing cask which I didn't have on my system after a new install of this cask, so I used wildcards to capture them.

From the [1.71.0 release notes](https://github.com/VSCodium/vscodium/releases/tag/1.71.0.22245):

> - Warning: Due to internal changes of build identifiers a manual update on MacOS is needed; on Win32 you may want to uninstall the old and install the new version - see https://github.com/VSCodium/vscodium/issues/1227

**Comment by toobuntu** [comment]
The second commit is a partial revert, as the quit is not desired.
This mirrors the treatment of cask `vscodium` https://github.com/Homebrew/homebrew-cask/pull/164857.

**Comment by miccal** [comment]
Thank you @toobuntu.

**Review by miccal — APPROVED** [review]

**Pull request merged**
