### PR TITLE
Add openshot-video-editor-daily

### PR DESCRIPTION
**Pull request by miccal**

### CODE REVIEW

**Comment by miccal** [comment]
@neutric are you able to test this, please?

**Comment by neutric** [comment]
> @neutric are you able to test this, please?

On it.

**Comment by neutric** [comment]
GUI opens fine. Livecheck is good, too.

**Comment by neutric** [comment]
```
  zap trash: [
    "~/.openshot_qt",
    "~/Library/Application Support/openshot",
    "~/Library/Preferences/openshot-qt.plist",
  ]
```

**Comment by miccal** [comment]
Thank you very much @neutric.

**Comment by neutric** [comment]
> Thank you very much @neutric.

Anytime!

**Pull request merged**
