### PR TITLE
Add AdoptOpenJDK 8

### PR DESCRIPTION
**Pull request by claui**
See discussion: https://github.com/Homebrew/homebrew-cask-versions/issues/7253#issuecomment-484494459

Note: This cask stays close to the [vendor’s cask](https://github.com/AdoptOpenJDK/homebrew-openjdk/blob/b08f38ed3c596dd6cf0506dfc33eac1a7cc05820/Casks/adoptopenjdk8.rb). I have modified it to interpolate more so it’s easier to maintain. See also: https://github.com/Homebrew/homebrew-cask-versions/pull/6415/files

___

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused]. **Note: It was removed in #6453 but needs to be re-added.**
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-versions/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by pqrth** [comment]
@claui, thanks for being one of the maintainers of this superb project *Homebrew*. The project is a lifeline for my macOS installations.

Now, could you please share why `adoptopenjdk8` is added to `homebrew/cask-version` when it is already available under `AdoptOpenJDK/openjdk`?

This change is causing following conflict if one has both the taps (Related issue: AdoptOpenJDK/homebrew-openjdk#106)

```
Error: Cask adoptopenjdk8 exists in multiple taps:
  homebrew/cask-versions/adoptopenjdk8
  adoptopenjdk/openjdk/adoptopenjdk8
```

**Comment by claui** [comment]
@pqrth We’re in the middle of moving AdoptOpenJDK casks to Homebrew’s own taps (which means that AdoptOpenJDK’s tap may become obsolete). Apologies for the hiccups in the meantime!

What happens if you install the cask by its fully qualified token? Does that help?

```
brew cask install homebrew/cask-versions/adoptopenjdk8
```

**Comment by Blaisorblade** [comment]
@claui That seems not enough. Here I get:
```
$ brew cleanup
Error: Cask adoptopenjdk8 exists in multiple taps:
  homebrew/cask-versions/adoptopenjdk8
  adoptopenjdk/openjdk/adoptopenjdk8
```

Luckily I can untap adoptopenjdk/openjdk for now.

**Comment by claui** [comment]
@Blaisorblade Yeah, that cleanup issue is a known hiccup in Homebrew. Apologies for the inconvenience.

**Comment by xuanranGit** [comment]
`$ brew cask install adoptopenjdk8
Error: Cask adoptopenjdk8 exists in multiple taps:
  homebrew/cask-versions/adoptopenjdk8
  caskroom/versions/adoptopenjdk8
  adoptopenjdk/openjdk/adoptopenjdk8`
I have same problem

**Comment by m-luo16** [comment]
> @claui That seems not enough. Here I get:
> 
> ```
> $ brew cleanup
> Error: Cask adoptopenjdk8 exists in multiple taps:
>   homebrew/cask-versions/adoptopenjdk8
>   adoptopenjdk/openjdk/adoptopenjdk8
> ```
> 
> Luckily I can untap adoptopenjdk/openjdk for now.

How do you do that?

**Comment by Blaisorblade** [comment]
@m-luo16 `brew untap adoptopenjdk/openjdk`; `brew help untap` and `man brew` explain more.

**Comment by reitermarkus** [comment]
@xuanranGit, you should also `brew untap caskroom/versions`.

**Pull request merged**
