### PR TITLE
Add WhatsApp Beta v2.2135.1

### PR DESCRIPTION
**Pull request by eloyaldea**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by eloyaldea** [comment]
Let's see if this is now OK, hope I didn't mess up my branches and commits 😅 .

**Comment by bevanjkay** [comment]
@eloyaldea This one is still opened from your `master` branch. [Here's some instructions that might help!](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#create-your-pull-request-from-a-new-branch)

**Comment by bevanjkay** [comment]
@eloyaldea [These instructions](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#submitting-your-changes) may be easier to follow as they are specific to `homebrew-cask`

**Comment by eloyaldea** [comment]
Thanks, let me figure out that I broke. I'm not very familiar with GitHub branches and PRs yet :/

**Comment by eloyaldea** [comment]
I have deleted my forked repo and forked it again, now I'm adding the new .rb file to my repo and making a PR, is that OK?

**Comment by bevanjkay** [comment]
You will need to create a new branch before you commit your changes.

Here is an example of the workflow steps in your terminal. If you are using VS Code or a GUI based GIt editor, make sure to create a new branch first.

```
git checkout -b add-whatsapp-beta

git add Casks/whatsapp-beta.rb

git commit -m "Add whatsapp-beta"

git push eloyaldea add-whatsapp-beta
```

**Comment by eloyaldea** [comment]
Yes I have seen those commands after following the instructions of adding a cask, but `git push eloyaldea add-whatsapp-beta` gives me this error:

> fatal: 'eloyaldea' does not appear to be a git repository
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by bevanjkay** [comment]
@eloyaldea What does terminal return if you run `git remote -v`

**Comment by eloyaldea** [comment]
From inside my `homebrew-cask-versions` folder, `git remote -v`shows:

> origin	https://github.com/Homebrew/homebrew-cask-versions (fetch)
> origin	https://github.com/Homebrew/homebrew-cask-versions (push)

**Comment by bevanjkay** [comment]
Run `git remote add eloyaldea https://github.com/eloyaldea/homebrew-cask-versions` and then try the push command again

**Comment by eloyaldea** [comment]
Done, it worked, now I have the `add-whatsapp-beta` branch in my fork, lets see if the PR is OK. Thanks man.

**Comment by bevanjkay** [comment]
@eloyaldea Just make sure you switch back to your master/main branch when you are done with `git switch master` or `git switch main`

**Pull request closed without merging**
