### PR TITLE
Revert "Update: temurin17.0.4.1 to 17.0.5"

### PR DESCRIPTION
**Pull request by miccal**
Reverts Homebrew/homebrew-cask-versions#14914

### CODE REVIEW

**Comment by carlocab** [comment]
Do we want to revert this? There's an Intel build.

**Comment by carlocab** [comment]
Or was #14914 merged without actually being ready to merge?

**Comment by miccal** [comment]
> Or was #14914 merged without actually being ready to merge?

It was not ready to be merged.

**Comment by zdtsw** [comment]
i shipped aarch64 for jdk17 about 20mins ago, which should be enough to make https://github.com/Homebrew/homebrew-cask-versions/pull/14914 complete
Probably we do not need to merge this revert any more?

**Pull request closed without merging**
