### PR TITLE
Replace open-uri with curl

### PR DESCRIPTION
**Pull request by Bo98**
The Homebrew/brew CI is constantly seeing flaky audit failures for `gpg-suite-nightly`. Upon further investigation, it appears that the DNS for releases.gpgtools.org contains multiple IPs, and some don't respond.

open-uri does not try another IP when one fails, but curl does. Curl also has better proxy and HTTPS support (there are known issues with open-uri certificate handling under portable-ruby). Moving to curl also aligns these network requests with what the rest of Homebrew does.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks for this @Bo98. I'd love a global rubocop that bans all use of `open-uri` in Homebrew/brew and all formulae/cask taps.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by Bo98** [comment]
I think the only cases left are:

* This
* Livecheck (https://github.com/Homebrew/brew/pull/10834)
* One in homebrew-services

**Comment by Bo98** [comment]
Or that's actually me searching for `require "open-uri"`. The better check is probably `URI#open` so maybe there's more.

**Comment by reitermarkus** [comment]
`curl_output` is a private API, it should not be in casks.

**Comment by Bo98** [comment]
Ok, I'll make sure they're not used across all other Homebrew taps and will disable the the relevant part of brew CI for now.

**Comment by Bo98** [comment]
And I'll also try to make sure `utils/curl` is not auto-required. Private API shouldn't be exposed like this - we do somewhat try to limit exposure in formulae.

**Comment by reitermarkus** [comment]
> not auto-required

What is required is pretty much impossible to enforce. The right solution would be to not have any global functions and instead explicitly include modules everywhere they're needed.

**Comment by MikeMcQuaid** [comment]
> `curl_output` is a private API

Let's make it a public API.

**Pull request merged**
