### PR TITLE
openzfs-dev: bump versions

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

### CODE REVIEW

**Comment by yurikoles** [comment]
Catalina test failed due to generic error about third-party kext.
Big Sur one fails with a known issue, it says that there are some third-party kexts left in the system, but they aren't coming from this cask.

**Comment by yurikoles** [comment]
Ping?

**Comment by SMillerDev** [comment]
Can you add a livecheck here?

**Comment by yurikoles** [comment]
> Can you add a livecheck here?

It's hard to me to imagine such a check. New versions are being posted in new threads on a forum. And version after comma is just an attachment ID. To say more: not all macOS versions is covered by all threads. E.g. arm64 build in separate thread, RC4 released only for Big Sur and Catalina.

**Review by miccal — APPROVED** [review]

**Pull request merged**
