### PR TITLE
Update wine-devel from 7.10 to 7.11

### PR DESCRIPTION
**Pull request by PythonCoderAS**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by Gcenx** [comment]
The scripts like `winecfg` need fixing up a little not sure if you want to handle this within the cask.

**Comment by PythonCoderAS** [comment]
@Gcenx I am not knowledgeable about how WINE works. I'll pass it off to someone else.

**Comment by Gcenx** [comment]
@PythonCoderAS uploaded both wine-devel & wine-staging archives with working scripts so just updating the checksums for both and you'll be good now.

**Comment by Gcenx** [comment]
All that’s needed for both of these is to update the checksums, the archives were repackaged with working scripts.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
