### PR TITLE
Add PostmanCanary.app v10.13.7-canary230510-0719

### PR DESCRIPTION
**Pull request by tedawf**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

I'm not very sure how to do the livecheck for this specifc app as I can't find a source that lists the version so I put skip for the livecheck. Hopefully someone more experienced can help with this as I am new here

### CODE REVIEW

**Comment by bevanjkay** [comment]
@tedawf I have updated the cask with a working livecheck, and versioned download url.
Can you explain the rationale behind the commented out lines in the `zap` stanza?

**Comment by tedawf** [comment]
Oh thank you! I was trying to figure out how to get a working livecheck, did not realise it was just an additional query params! 

The commented out zaps are because I took them from the `postman` cask and since both the postman and the postman-canary can be installed side-by-side, I did not want `brew uninstall --zap postman-canary` to affect users with the `postman` cask installed as well. However, on my own device, I could not find any other areas where `postman-canary` has associated files except that one location.

**Comment by bevanjkay** [comment]
@tedawf In that case, let's just remove the lines from the zap rather than comment them out.

**Comment by tedawf** [comment]
Done! Let me know if there are any other issues with the cask

**Comment by miccal** [comment]
Thank you @tedawf.

**Review by miccal — APPROVED** [review]

**Comment by bevanjkay** [comment]
@miccal I think in this case because it is a prerelease, `postman-canary` would be the correct token for consistency with other casks and the `homebrew-cask-versions` [guidelines](https://github.com/Homebrew/homebrew-cask-versions/blob/master/CONTRIBUTING.md#naming-versions-casks).

**Comment by miccal** [comment]
I believe the token reference always takes first priority.

**Comment by bevanjkay** [comment]
My assumption is that the `homebrew-cask-versions` guidelines should take priority here because the docs refers to them as "exceptions" to the main repo instructions.

**Pull request merged**
