### PR TITLE
Create mos3.rb

### PR DESCRIPTION
**Pull request by KhushrajRathod**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for an unstable version

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-versions/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but we’re not going to accept a link from a random issue. When they make it a release, we can reconsider.

**Comment by KhushrajRathod** [comment]
@vitorgalvao Hi, I don't think that's a random issue. It's the next version of Mos in public beta, and Mos (stable) already exists on homebrew-casks.

**Comment by vitorgalvao** [comment]
> I don't think that's a random issue. It's the next version of Mos in public beta

It’s still a random issue. The amount of people that’ll find it is way lower than if it had a dedicated page or release. That’s what the pre-release tag is for and they know how to use (they do so for `2.4.0`).

> Mos (stable) already exists on homebrew-casks.

That in no way guarantees it entry into this repo. I refuse casks to this repo all the time because they’re not popular enough on the main repo. [We have strict rules for what goes into this one](https://github.com/Homebrew/homebrew-cask-versions#acceptable-casks).

> The download itself comes from the releases section

No, it comes from a directory in the repo called `Release`. Not the same.

**Comment by KhushrajRathod** [comment]
Oh. Sorry... Thank you for taking time to review the request 😄

**Pull request closed without merging**
