### PR TITLE
Update dotnet-sdk-preview from 5.0.100-preview.8.20417.9 to 5.0.100-rc.1.20452.10

### PR DESCRIPTION
**Pull request by externl**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask-versions/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by miccal** [comment]
@externl would you happen to know if there are major differences between a "preview" and a "release candidate"?

**Comment by externl** [comment]
Not sure what you'd classify as major but there were some changes which are not available in preview 8 (and some things removed).

**Comment by miccal** [comment]
@externl would you happen to know if there are major differences between a "preview" and a "release candidate"?

I am wondering if this should be re-named to 

> Not sure what you'd classify as major but there were some changes which are not available in preview 8 (and some things removed).

Thanks @externl.

@vitorgalvao thought concerning the name? Perhaps we should have a new Cask called `dotnet-sdk-release-canditate` or `dotnet-sdk-rc`?

**Comment by externl** [comment]
I think they plan on releasing .NET 5 soon-ish so I don't think changing the name really necessary (not sure what you guys usually for this type of issue). I think the .NET people expect the latest version to be used and it's not like they support preview 8 anymore.

**Comment by externl** [comment]
They still like to use `preview` at lot to reference this release. 
* https://github.com/dotnet/core/tree/master/release-notes/5.0/preview — folder name is preview
* https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-rc.1.md — calling it the .NET SDK 5.0.100 preview

🤷‍♂️

**Comment by vitorgalvao** [comment]
I’m fine with keeping it as is. I don’t really imagine there’s any demand for *both* a `preview` and `rc` casks. Anyone wanting one of these probably means “whatever is coming”.

```
dotnet-sdk-preview
30 days: 42 (#1125)
90 days: 92 (#1342)
365 days: 241 (#2118)
Age: 742 days (added 2018, September 27)
```

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
