### PR TITLE
Bump picoscope beta 7.0.90

### PR DESCRIPTION
**Pull request by flieger19**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@flieger19 Please keep the box ticked to allow maintainers to push to your PR, so we can help with minor adjustments.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by miccal** [comment]
Please replace the line
```
uninstall pkgutil: "com.picotech.picoscope#{version.major}"
```
with
```
uninstall pkgutil: "com.picotech.picoscope#{version.major}tnmbeta"
```

**Comment by miccal** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask-versions/pull/13112

**Comment by flieger19** [comment]
Sorry guys, I had serious problems with the local repository so I had to fix them first. Many Thanks for your support.

**Pull request closed without merging**
