### PR TITLE
Update verified parameter – group 2

### PR DESCRIPTION
**Pull request by gtmgianni**
Converts verified comment to verified parameter of `url`

### CODE REVIEW

**Comment by vitorgalvao** [comment]
What I meant was 20 or 30 **PRs** at a time, one per cask. So we could fix them as they came and didn’t have to keep skipping checks on these.

**Comment by gtmgianni** [comment]
> What I meant was 20 or 30 PRs at a time, one per cask. So we could fix them as they came and didn’t have to keep skipping checks on these.

Ah, my apologies, I misunderstood. I'll adjust the script accordingly and submit more PRs later.

**Comment by vitorgalvao** [comment]
> Ah, my apologies, I misunderstood.

Apologies on my side for not having been clearer!

**Review by miccal — APPROVED** [review]

**Pull request merged**
