### PR TITLE
Geogebra5

### PR DESCRIPTION
**Pull request by y0d0gawaeuc11d**
Geogebra v5 provides with some features that v6 lacks and most of Mac apps usually have (ex. easy to save and open files, shortcuts, etc). So it's worth joining homebrew🤔

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install <cask>` worked successfully.
- [x] `brew uninstall <cask>` worked successfully.

### CODE REVIEW

**Review by bevanjkay — COMMENTED** [review]
@y0d0gawaeuc11d  thank you.
Can you please update the PR and include a conflicts_with stanza for the main geogebra cask? We should also do the same on the main geogebra cask.

`conflicts_with cask: "geogebra"`

**Comment by y0d0gawaeuc11d** [comment]
@bevanjkay Thank you for reviewing.
I often run Geogebra 5 and 6 simultaneously and apparently I find no conflicts.
Is it preferable to add conflicts_with stanza in case?

**Comment by bevanjkay** [comment]
@y0d0gawaeuc11d My apologies, I had misread that the Geogebra cask also installed with the same filename, I will merge this in now. Thanks!

**Review by bevanjkay — APPROVED** [review]

**Comment by y0d0gawaeuc11d** [comment]
@bevanjkay Thanx for merging!

**Pull request merged**
