### PR TITLE
Update iterm2-nightly to 3_3_20190210

### PR DESCRIPTION
**Pull request by gnachman**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by reitermarkus** [comment]
This doesn't have an appcast nor a versioned URL.

**Comment by vitorgalvao** [comment]
We could use `https://github.com/gnachman/iTerm2/releases` as an `appcast`.

However, even though you’re the developer, @gnachman, we prefer to have nightlies unversioned, as otherwise the constant barrage of updates would make updating them too problematic.

**Comment by gnachman** [comment]
I think my script is broken anyway, so I'll remove the cask-repair command from it.

**Comment by vitorgalvao** [comment]
@gnachman But if you have a script that submits the stable iTerm2 versions to the main repo (https://github.com/Homebrew/homebrew-cask) as they come out, those PRs we’ll be happy to receive!

**Pull request closed without merging**
