### PR TITLE
Add WhatsApp Beta v2.2135.1

### PR DESCRIPTION
**Pull request by eloyaldea**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by eloyaldea** [comment]
I did my best to make a good PR to add WhatsApp Beta to Homebrew and followed the contributing guide etc. I'm sure there are more checks and things needed to the .rb file for it to be in perfect condition but I wasn't familiar with all of them so I stayed with [this contributing guide](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md). Hope it works!

**Comment by bevanjkay** [comment]
@eloyaldea Thanks for your submission.
You should be able to have a look at the [`whatsapp`](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/whatsapp.rb) cask from the `homebrew-cask` repository and modify the livecheck, and most likely use the zap stanza as it should still apply here.

**Comment by eloyaldea** [comment]
Hi, I have copied the livecheck from [`whatsapp`](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/whatsapp.rb) and it is now able to fetch the versions. I have also copied the `zap` stanza from [`whatsapp`](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/whatsapp.rb) as well and commited the changes to the `whatsapp-beta.rb` file.

**Comment by bevanjkay** [comment]
@eloyaldea Can you please close this PR and open a new one that is on a branch of your `homebrew-cask-versions` fork. Maintainers do not have access to commit to the PR, so that we can fix some small issues.

**Comment by eloyaldea** [comment]
Sure, hope I can manage 😅 it took me a while to get this PR 😂 .

**Comment by bevanjkay** [comment]
@eloyaldea No worries. You can comment back here if you get stuck 👍🏻

**Pull request closed without merging**
