### PR TITLE
Add arm64 specific version for visual studio code insiders

### PR DESCRIPTION
**Pull request by mnin**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

### CODE REVIEW

**Comment by thecesrom** [comment]
Sorry to intrude, but I hadn't noticed this PR when I opened #10210 and I was wondering if the `appcast` stanza specific to `amd64` should also be added.

64 bit:
```ruby
  appcast "https://update.code.visualstudio.com/api/update/darwin/insider/VERSION"
```

ARM64:
```ruby
  appcast "https://update.code.visualstudio.com/api/update/darwin-arm64/insider/VERSION"
```

So it would look something like this:
```ruby
cask "visual-studio-code-insiders" do
  if Hardware::CPU.intel?
    version "1.53.0,3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e"
    sha256 "47747b302d5f3d3245c1d45d99db326497c94148bd63356f8395b0763bc300d3"

    url "https://az764295.vo.msecnd.net/insider/#{version.after_comma}/VSCode-darwin.zip",
        verified: "az764295.vo.msecnd.net/insider/"
    appcast "https://vscode-update.azurewebsites.net/api/update/darwin/insider/VERSION"
  else
    version "1.53.0,e17aea136d32fdb06d9b32184b04ccd36bb51e9c"
    sha256 "3f9bdb6867636cc9116d96a09aef53a927e1636609df33bfe23a1275107a04b6"

    url "https://az764295.vo.msecnd.net/insider/#{version.after_comma}/VSCode-darwin-arm64.zip",
        verified: "az764295.vo.msecnd.net/insider/"
    appcast "https://update.code.visualstudio.com/api/update/darwin-arm64/insider/VERSION"
  end
  name "Microsoft Visual Studio Code"
  name "VS Code - Insiders"
  desc "Integrated development environment"
  homepage "https://code.visualstudio.com/insiders"

  auto_updates true

  app "Visual Studio Code - Insiders.app"
  binary "#{appdir}/Visual Studio Code - Insiders.app/Contents/Resources/app/bin/code", target: "code-insiders"

  zap trash: [
    "~/Library/Application Support/Code - Insiders",
    "~/Library/Caches/Code - Insiders",
    "~/Library/Caches/com.microsoft.VSCodeInsiders",
    "~/Library/Caches/com.microsoft.VSCodeInsiders.ShipIt",
    "~/Library/Preferences/com.microsoft.VSCodeInsiders.helper.plist",
    "~/Library/Preferences/com.microsoft.VSCodeInsiders.plist",
  ]
end
```

**Comment by mnin** [comment]
@thecesrom done

**Review by vitorgalvao — APPROVED** [review]

**Comment by thecesrom** [comment]
@vitorgalvao 

I would assume that `brew bump-cask-pr` is no longer an option for bumping this Cask. Or is it?

**Comment by vitorgalvao** [comment]
@thecesrom That’s a good point. Asking @SeekingMeaning.

**Comment by thecesrom** [comment]
Thanks, @vitorgalvao. I started [discussion 561](https://github.com/Homebrew/discussions/discussions/561) to discuss this situation.

**Pull request merged**
