### PR TITLE
Create java12.rb

### PR DESCRIPTION
**Pull request by michl-b**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].
- [x] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-versions/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

### CODE REVIEW

**Comment by michl-b** [comment]
Hi guys, is there a reason why this is not merged. 
I would appreciate an update on this. 
Thanks

**Comment by martinpallmann** [comment]
I updated my home-brew and suddenly I haven't java12 anymore, which is really bad, since my project depends on it and doesn't work on java13 yet. Please could you perhaps considering merging this PR?

**Comment by fastily** [comment]
@michl-b I get the impression that all java-related casks are on hold until https://github.com/Homebrew/homebrew-cask/issues/57387 is resolved

**Comment by vitorgalvao** [comment]
> @michl-b I get the impression that all java-related casks are on hold until [Homebrew/homebrew-cask#57387](https://github.com/Homebrew/homebrew-cask/issues/57387) is resolved

Pretty much. We’re only merging simple updating PRs.

**Comment by martinpallmann** [comment]
The upgrade from java12 to java13 unfortunately is not simple, because there are problems with Scala macros so I can’t build my project anymore with Java 13 and I can’t downgrade to 12 because there is no cask for that. Well, I‘m sure I‘ll find a solution. But that was not nice from a ux perspective. 🙁

**Comment by vitorgalvao** [comment]
> and I can’t downgrade to 12 because there is no cask for that.

You can install it manually, which is exactly what you’d do if Homebrew Cask didn’t exist. Us not providing a cask is never an impediment to installing the software you need.

> But that was not nice from a ux perspective.

What’s even worse is maintainers having to bang their heads all the time because there are umpteen ways to get different incompatible variants and versions of java and the community being split in about as many ways.

We keep this project running for free on our free time, and no maintainer is happy with the java-created mess. That’s not our fault, yet we get the complaints. I’m confident you can appreciate how that’s exhausting and can make us less motivated to work on it.

**Comment by bosyi** [comment]
if anyone interested i pushed this cask here https://github.com/bosyi/homebrew-cask-goodies/blob/master/Casks/java12.rb

**Comment by reitermarkus** [comment]
Closing this, since there is now an `openjdk@12` formula.

**Pull request closed without merging**
