### PR TITLE
Update mono-mdk-for-visual-studio.rb

### PR DESCRIPTION
**Pull request by robertleeblairjr**
As of today, this is the specific version for stable on Visual Studio 2019 for macOS.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by robertleeblairjr** [comment]
I wasn't able to push a git checkout for this branch because it was exiting with Error: Failure 128. But, for some reason git checkout is working on other branches and files. So, maybe it's pertaining to this branch or file only. Anyways, this is the stable version as provided by screenshots.

Screen Shot 2022-01-09 at 7 21 02 AM

Screen Shot 2022-01-09 at 7 22 35 AM

**Comment by robertleeblairjr** [comment]
Maybe changing the livecheck back to the mono-project website even though they never keep that updated. At least with the version which comes via the visual studio installer, then it can be updated to the latest version via the installer or app instead of having conflicts. Because, there's no real solution which helps keep the tagged releases up to date other than the maintainers for Mono on their site. And they haven't changed their practice in at least the last 2-3 years of keeping the channel updated for the correct versioning.

**Comment by miccal** [comment]
@robertleeblairjr I do not quite understand what you are doing here -- why have you downgraded the version, and what is the issue with fetching the latest available version from `https://download.mono-project.com/archive/#{version.major_minor_patch}/macos-10-universal/`?

**Comment by robertleeblairjr** [comment]
> @robertleeblairjr I do not quite understand what you are doing here -- why have you downgraded the version, and what is the issue with fetching the latest available version from `https://download.mono-project.com/archive/#{version.major_minor_patch}/macos-10-universal/`?

Read my original comment from the PR. This version is not the release version used by VS. It's 6.12.0.162. The version on their webpage is 6.12.0.122. This problem of mismatching and never staying updated by Mono devs on their site has occurred for years. There's no changing it. So, I was suggesting to move back to just tracking the version on their webpage, even if older, and allowing whomever to update their version through the VS app if they choose to. Otherwise, you'll left with installing this newer version and downgrading with the app.

**Comment by miccal** [comment]
> Read my original comment from the PR.

I did :)

> 6.12.0.162

So why have you downgraded it to `6.12.0.122`?

**Comment by miccal** [comment]
I am getting very tired of the issues with this Cask.

I have added a comment above the `livecheck` block to state that this Cask will only track the version shown on the download page, no matter how "outdated" it supposedly is.

In the future, any PR's that the update this Cask to a version that differs to that shown by the `livecheck` will be closed.

**Pull request merged**
