### PR TITLE
Add missing conflicts_with for android-studio-preview-canary

### PR DESCRIPTION
**Pull request by tir38**
After making all changes to a cask, verify:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask-versions/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Derp, #9134 got closed before I could rebase. So here it is again.

### CODE REVIEW

**Comment by yurikoles** [comment]
I had reviewed CI logs and all of them are unrelated. Travis CI says that homepage is unreachable, but there is more recent PR that was tested and merged without issue a couple of hours ago. And there was temporary error in GH Action git config, that also caused other cask's CI to fail. 

Could you please trigger a re-test? Because @BrewTestBot ignores my requests. Maybe because I have no right to trigger it.

**Comment by ouchadam** [comment]
@tir38 👋  what was the reason for adding this? it now means it's no longer possible to run android studio stable and preview side by side (unless I'm missing something 🤔 )

**Comment by tir38** [comment]
@ouchadam good question. I think I misunderstood the initial request here: https://github.com/Homebrew/homebrew-cask-versions/pull/9134#issuecomment-630241801

I will update both preview-canary and preview-beta to remove the conflics_with on stable

**Comment by tir38** [comment]
@ouchadam 
https://github.com/Homebrew/homebrew-cask-versions/pull/9510 Canary
https://github.com/Homebrew/homebrew-cask-versions/pull/9509 Beta

**Comment by ouchadam** [comment]
@tir38 thanks!! 🎉

**Pull request merged**
