### PR TITLE
temurin11 11.0.22

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
There's no Intel build for this in the GitHub release.

**Comment by Bo98** [comment]
Still be worked on: [adoptium/temurin#17](https://redirect.github.com/adoptium/temurin/issues/17)

**Comment by Haroon-Khel** [comment]
@chenrui333 Feel free to recreate this pr, jdk11 intel and arm mac have both been released https://github.com/adoptium/temurin/issues/17

**Comment by p-linnane** [comment]
It appears there is now a `7.1` release, which does not have Intel binaries now. This is causing a new failure.

**Comment by Bo98** [comment]
Might be a arm64-specific rerelease, though this is a guess given I can't find any documentation on the release.

**Comment by Haroon-Khel** [comment]
Yes, arm64 was republished with a `.1`, while intel was not. Is it not possible to have separate version numbers for intel and arm in this file?

**Comment by p-linnane** [comment]
We can, but will need to change it back on the next release.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
