### PR TITLE
Add Pext nightly

### PR DESCRIPTION
**Pull request by TheLastProject**
I have not been able to check everything because I currently do not have access to my macOS machine.

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-versions/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> curl: (22) The requested URL returned error: 404 Not Found
audit for pext-nightly: failed
 > - download not possible: Download failed on Cask 'pext-nightly' with message: Download failed: https://github.com/Pext/Pext/releases/continuous/Pext-.dmg
> - The URL https://github.com/Pext/Pext/releases/continuous/Pext-.dmg is not reachable (HTTP status code 404)
> - Casks with an appcast should not use version :latest

**Comment by TheLastProject** [comment]
Seems fine now :)

**Comment by TheLastProject** [comment]
I think the 403 forbidden errors are simply due to the GitHub API being rate-limited and the Travis IP probably reaching that, one of the attempts worked fine: https://travis-ci.org/Homebrew/homebrew-cask-versions/builds/481873233.

**Comment by vitorgalvao** [comment]
> I think the 403 forbidden errors are simply due to the GitHub API being rate-limited and the Travis IP

Agreed. This is passing fine locally. Thank you for your work.

**Pull request merged**
