### PR TITLE
Revert "Delete microsoft-remote-desktop-beta.rb"

### PR DESCRIPTION
**Pull request by lumaxis**
Adding microsoft-remote-desktop-beta back with a fixed Formula.

### CODE REVIEW

**Comment by miccal** [comment]
@lumaxis this is not going to work -- if you check [this issue](https://github.com/Homebrew/homebrew-cask/issues/80779) the problem here is that HockeyApp links redirect to App Center links and the redirects are unstable.

**Comment by lumaxis** [comment]
Thanks @miccal, I've read the issue thoroughly 🙂 
I had at first falsely remembered that we had built in support for specific versions in the legacy API support for HockeyApp which would have made this PR work just fine.
Now I just realized that the API for simplicity always returns the latest available version.

That said, the redirect is stable in the way that https://rink.hockeyapp.net/api/2/apps/5e0c144289a51fca2d3bfa39ce7f2b06?format=zip always returns to a working download URL, it just doesn't support requesting specific versions. So an unversioned Cask Formula would theoretically still work.

**Comment by vitorgalvao** [comment]
Hockeyapp is dead and links are starting to redirect to appcenter. Even if this works now, it won’t for long. We need a long-term solution.

**Comment by lumaxis** [comment]
@vitorgalvao I'm very aware, I worked on both and am still on the team at Microsoft that owns App Center. Was just trying to experiment with possible temporary solutions while I try to convince the stakeholders to add a permanent one 😊

**Comment by vitorgalvao** [comment]
Unfortunately, in my experience temporary solutions in casks more often than not become permanent hacks that are abandoned and left for us to fix when they break and no one even remembers them anymore.

If you can get the decision makers to make appcenter URLs that aren’t averse to direct CLI downloads, you’d be helping a lot of casks and their users. But we’re not able to rely on a “may happen”, especially on the versions repo, which is less organised.

**Comment by lumaxis** [comment]
That’s perfectly fair and completely understandable. Part of the motivation for this PR was also my own curiosity and trying to understand again how our own system works 😄

I’ll ask around on the team next week and reach out when I learn more!

**Pull request closed without merging**
