### PR TITLE
Update android-studio-preview-beta from 2021.2.1.11 to 2021.2.1.12

### PR DESCRIPTION
**Pull request by hannesbraun**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@hannesbraun It looks like this will now need a `conflicts_with "android-studio"` if the app name has changed to match the main cask - https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/android-studio.rb

**Comment by hannesbraun** [comment]
Yes, I forgot about that. Sorry. It should be fixed now.

**Comment by bevanjkay** [comment]
@hannesbraun After this is mergedcan you please do the same in the main cask?

**Comment by hannesbraun** [comment]
> @hannesbraun After this is mergedcan you please do the same in the main cask?

Done

**Pull request merged**
