### PR TITLE
tap_migrations: migrate some casks to `homebrew/cask`

### PR DESCRIPTION
**Pull request by cho-m**
* `brave-browser-beta`
* `brave-browser-dev`
* `brave-browser-nightly`
* `google-chrome-beta`
* `google-chrome-canary`
* `google-chrome-dev`
* `microsoft-edge-beta`
* `microsoft-edge-dev`

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=pullrequests).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by cho-m** [comment]
Depends on https://github.com/Homebrew/homebrew-cask/pull/172349

Also should probably make sure Casks are visible over API before merging.

**Review by razvanazamfirei — APPROVED** [review]

**Comment by cho-m** [comment]
Available via API:
```
❯ unset HOMEBREW_NO_INSTALL_FROM_API

❯ brew info google-chrome@canary
==> google-chrome@canary: latest
https://www.google.com/chrome/canary/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/g/google-chrome@canary.rb
==> Name
Google Chrome Canary
==> Description
Web browser
==> Artifacts
Google Chrome Canary.app (App)
```

**Comment by bartekpacia** [comment]
Hey @razvanazamfirei, where can I learn more about this migration? Thanks in advance!

**Comment by razvanazamfirei** [comment]
Thanks @bartekpacia! See [here](https://github.com/Homebrew/homebrew-cask-versions/issues/19665) for more details. Briefly, we're going to migrate all non-deprecated casks from this repository to the main repository.

**Pull request merged**
