### PR TITLE
Add Microsoft Edge Canary v76.0.161.0

### PR DESCRIPTION
**Pull request by ljtill**
After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-versions/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by ljtill** [comment]
Receiving the following error on the build 'string contains null byte', checked install / uninstall and not receiving any errors.

**Comment by vitorgalvao** [comment]
> string contains null byte

That’s a common error with microsoft software. We don’t know the cause but are pretty sure it’s on their side.

It says on the website this build is updated daily. That’s too much of an update burden. This needs to use a [`url` block](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#urls-that-change-on-every-visit) instead.

**Comment by coreygo** [comment]
The url `…/MacAutoupdate/…` suggests `auto_updates true` may also be helpful. Or am I wrong?

**Comment by vitorgalvao** [comment]
> The url `…/MacAutoupdate/…` suggests `auto_updates true` may also be helpful. Or am I wrong?

`auto_updates true` just means the software auto-updates in your system, it does nothing to keep the cask itself up to date.

**Comment by coreygo** [comment]
Right, but tools like [homebrew-cask-upgrade](https://github.com/buo/homebrew-cask-upgrade) make use of the `auto_updates true` setting. Just a thought, all other Microsoft casks I've installed have it set.

**Comment by ljtill** [comment]
> The url `…/MacAutoupdate/…` suggests `auto_updates true` may also be helpful. Or am I wrong?

Thanks @coreygo I've added this block

**Comment by ljtill** [comment]
> > string contains null byte
> 
> That’s a common error with microsoft software. We don’t know the cause but are pretty sure it’s on their side.
> 
> It says on the website this build is updated daily. That’s too much of an update burden. This needs to use a [`url` block](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#urls-that-change-on-every-visit) instead.

Thanks @vitorgalvao - looks like from the commits you've added that suggestion already but the error still exists in the build.

**Comment by vitorgalvao** [comment]
> tools like [homebrew-cask-upgrade](https://github.com/buo/homebrew-cask-upgrade) make use of the `auto_updates true` setting

So does our own `brew cask upgrade`. The linked software is not official and not supported by us.

I think I misunderstood your first comment. I thought it was in reply to “[t]his needs to use a [`url` block](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#urls-that-change-on-every-visit)”.

> we still have an error in the build.

As I said, that’s common with Microsoft software and we don’t know the cause. Ignore it; it won’t stop us from merging the cask because we know it fails in Travis but not outside of it. What we do need is the `url` block.

**Comment by nicerloop** [comment]
I got the appcast URL and extracted the version from it:

  module Utils
    def self.file_version
      require 'open-uri'
      appcast = 'https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409EDCN01-chk.xml'
      appcast_version = open("#{appcast}").read.split(/\n+/).grep(/<string>/).last.scan(/<string>(.*)<\/string>/)[0][0].split('.')
      file_version = appcast_version[0] + ".0." + appcast_version[1] + ".0"
      end
  end

  version "#{Utils.file_version}"
  sha256 :no_check
``

**Comment by ljtill** [comment]
Thanks @nicerloop, I've incorporated your changes into the Cask and added the url block.

**Comment by eveenendaal** [comment]
FYI, looks like the dev channel has been release. https://www.microsoftedgeinsider.com/en-us/download/

**Comment by coreygo** [comment]
@eveenendaal thanks, just submitted… #7449

FYI to others, app_cast URL info found here:
https://github.com/pbowden-msft/OfficeCDNCheck/blob/master/OfficeCDNCheck#L37

**Pull request merged**
