### PR TITLE
wine-devel 9.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by YupItzAfi** [comment]
Should add this👍

**Review by YupItzAfi — COMMENTED** [review]
gstreamer issue is with homebrew, not with wine-devel

**Comment by p-linnane** [comment]
Tried the same approach that worked for https://github.com/Homebrew/homebrew-cask-versions/pull/19493, but there are only 3 binaries in the `bin` folder for this version. I'm not sure if that is intentional or not.

**Comment by YupItzAfi** [comment]
Then why would they remove winedbg winecfg etc too...

**Comment by p-linnane** [comment]
Thank you very much @Gcenx. Your help is very appreciated.

**Comment by YupItzAfi** [comment]
@Gcenx sorry, my bad, thanks either way!

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
