### PR TITLE
deadbeef-devel: fix case-sensitivity in app artifact, add description

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

### CODE REVIEW

**Comment by yurikoles** [comment]
Can we move this to main repo since app there is no stable version for yet for years?

**Comment by yurikoles** [comment]
And to clarify: @homebrew/cask is there some rule on download count? A lot of casks that I used was silently removed without a commit, so, in this case an app's [repo](https://github.com/DeaDBeeF-Player/deadbeef) is notable enough: 130 forks, 56 watchers, 1k stars, but it has only 168 in last year. The app's main platform is Linux, macOS and Windows builds wasn't promoted to stable for years.

**Comment by yurikoles** [comment]
How to ping a team here? Is it only allowed to existing maintainers to ping a whole team?
Ok, `sudo ping` @vitorgalvao

**Comment by vitorgalvao** [comment]
> Can we move this app to main repo since there is no stable version for yet for years?

Yes. Seems like there aren’t any stable builds, so this should’ve been added there in the first place (without `-devel`).

> How to ping a team here? Is it only allowed to existing maintainers to ping a whole team?

I think I’ve asked you this before, but please don’t ping maintainers (let alone a whole group!) so soon after making a PR—let alone on a holiday—unless you’re making a critical fix. This could very well wait (even for weeks), we’d have gotten to it.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
