### PR TITLE
firefox-esr 115.0.2

### PR DESCRIPTION
**Pull request by teenigma**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
This cask is for Firefox ESR, which is the extended support version. You are trying to update it to the standard release. That is available in `homebrew-cask` as `firefox`.

**Comment by teenigma** [comment]
Firefox 115.0.2 ESR was [recently released](https://www.mozilla.org/en-US/firefox/115.0.2esr/releasenotes/)

**Comment by p-linnane** [comment]
Though the page provides the release notes, the download itself is still for 102.13.0esr. Once they begin serving the new version we can revisit this.

**Comment by Bo98** [comment]
I think the confusing part is there's two ESR channels. "ESR" and "ESR Next".

Currently "ESR" is 102 and "ESR Next" is 115. In a couple months "ESR" will point to 115 and "ESR Next" will be retired until next summer.

I guess debatable what one we track, but the primary download on Firefox's website is 102, and you have to dig deeper to find 115.

**Comment by p-linnane** [comment]
Definitely think we should go with the version that is served without digging.

**Pull request closed without merging**
