### PR TITLE
Add WhatsApp Beta v2.2135.1

### PR DESCRIPTION
**Pull request by eloyaldea**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
PR is perfect @eloyaldea 👌🏻

**Comment by eloyaldea** [comment]
Happy to hear that, I have pushed many updates for casks using `bump-cask-pr` as you can see, but never having added a cask I had a bit of a mess understanding my local files, my commits, my pushes, my forks... etc, so many thanks for the help and taking your time trying to fix this 😄

**Review by bevanjkay — DISMISSED** [review]

**Review by bevanjkay — APPROVED** [review]

**Comment by miccal** [comment]
Thank you @eloyaldea.

**Comment by eloyaldea** [comment]
Yessss, thanks guys, and happy to help as always!

**Pull request merged**
