### PR TITLE
Update azure-data-studio-insiders from 1.30.0,d04451985c5fcab79a2c51ef5c5d90a703872432 to 1.30.0,d8b693341e814e792dbb644ded52ec1632b60c2c

### PR DESCRIPTION
**Pull request by thecesrom**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by thecesrom** [comment]
Not sure what happened on the `brew audit --cask` step of the CI workflow, but "it works on my machine".

Your help is much appreciated.

```zsh
$ brew audit --cask --appcast --online './Casks/azure-data-studio-insiders.rb'
==> Downloading https://sqlopsbuilds.azureedge.net/insider/d8b693341e814e792dbb644ded52ec1632b60c2c/azuredatastudio-macos-1.30.0-insider.zip
######################################################################## 100.0%
audit for azure-data-studio-insiders: passed
```

And with `--debug` and `--verbose`:

```zsh
$ brew audit --cask --appcast --online --debug --verbose './Casks/azure-data-studio-insiders.rb'
git config --get homebrew.devcmdrun
/usr/bin/env XDG_CACHE_HOME=/Users/thecesrom/Library/Caches/Homebrew/style /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby /usr/local/Homebrew/Library/Homebrew/utils/rubocop.rb --format json --force-exclusion --parallel --extra-details --display-cop-names --except FormulaAuditStrict --config /usr/local/Homebrew/Library/.rubocop.yml /Users/thecesrom/github/thecesrom/Homebrew/cask-versions/Casks/azure-data-studio-insiders.rb
==> Auditing Cask azure-data-studio-insiders
==> Auditing required stanzas
==> Verifying version :latest does not appear as a string ('latest')
==> Verifying sha256 :no_check with version :latest
==> Verifying sha256 string is a legal SHA-256 digest
==> Verifying sha256 is not a known invalid value
==> Auditing URL format
==> Auditing download
==> Downloading https://sqlopsbuilds.azureedge.net/insider/d8b693341e814e792dbb644ded52ec1632b60c2c/azuredatastudio-macos-1.30.0-insider.zip
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.1.11-10-g71bee26\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://sqlopsbuilds.azureedge.net/insider/d8b693341e814e792dbb644ded52ec1632b60c2c/azuredatastudio-macos-1.30.0-insider.zip
Already downloaded: /Users/thecesrom/Library/Caches/Homebrew/downloads/593c32b6d6669e76de39916d62008e78b9e90a97d78c28df882d73003578bcd7--azuredatastudio-macos-1.30.0-insider.zip
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/thecesrom/Library/Caches/Homebrew/downloads/593c32b6d6669e76de39916d62008e78b9e90a97d78c28df882d73003578bcd7--azuredatastudio-macos-1.30.0-insider.zip
/usr/bin/xattr -p com.apple.quarantine /Users/thecesrom/Library/Caches/Homebrew/downloads/593c32b6d6669e76de39916d62008e78b9e90a97d78c28df882d73003578bcd7--azuredatastudio-macos-1.30.0-insider.zip
==> /Users/thecesrom/Library/Caches/Homebrew/downloads/593c32b6d6669e76de39916d62008e78b9e90a97d78c28df882d73003578bcd7--azuredatastudio-macos-1.30.0-insider.zip is quarantined
==> Verifying checksum for cask 'azure-data-studio-insiders'
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.1.11-10-g71bee26\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --dump-header - --output /private/tmp/20210608-6853-1hibcn9 --location --connect-timeout 15 --max-time 25 --retry-max-time 25 https://sqlopsbuilds.azureedge.net/insider/d8b693341e814e792dbb644ded52ec1632b60c2c/azuredatastudio-macos-1.30.0-insider.zip
/usr/bin/curl --disable --globoff --show-error --user-agent Mozilla/5.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10_12_3\)\ AppleWebKit/602.4.8\ \(KHTML,\ like\ Gecko\)\ Version/10.0.3\ Safari/602.4.8 --header Accept-Language:\ en --retry 3 --dump-header - --output /private/tmp/20210608-6853-1pfszc9 --location --connect-timeout 15 --max-time 25 --retry-max-time 25 https://docs.microsoft.com/en-us/sql/azure-data-studio/
==> Auditing preflight and postflight stanzas
==> Auditing single uninstall_* and zap stanzas
==> Auditing pkg stanza: allow_untrusted
==> Auditing stanzas which require an uninstall
==> Auditing GitHub prerelease
audit for azure-data-studio-insiders: passed
```

**Comment by carlocab** [comment]
Maybe just a random network failure. You wouldn't happen to have `HOMEBREW_FORCE_BREWED_CURL` set, would you?

**Comment by thecesrom** [comment]
> Maybe just a random network failure. You wouldn't happen to have `HOMEBREW_FORCE_BREWED_CURL` set, would you?

I don't have that.

**Comment by thecesrom** [comment]
Thanks for your help, @carlocab. 🙇🏽‍♂️

**Pull request merged**
