### PR TITLE
Update clashx-pro from 1.95.1.1 to 1.96.1.1

### PR DESCRIPTION
**Pull request by scorpig**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @scorpig.

**Comment by goalidea** [comment]
is clashx-pro download url right? brew upgrade --cask --greedy clashx-pro error
log: curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to appcenter.vercel.app:443

**Comment by miccal** [comment]
Working for me:
```
|-> brew fetch clashx-pro
==> Downloading https://appcenter.vercel.app/clashx/clashx-pro/1.96.1.1
==> Downloading from https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/d347cf90-263b-44c9-b695-dd438e000504/ClashX.dmg?sv=2019-02-02&sr=c&sig=EiyYH8r99wF%2Bc3gMZ3MeN1TAUCf3xaAAX3YFYNcr31s%3D&se=2022-11-26T14%3A01%3A17Z&sp=
######################################################################## 100.0%
Downloaded to: /Users/miccal/Library/Caches/Homebrew/downloads/4c93d0b03db3041f0bd7dce9f6c46a2f5fc1efc2766ae0e1f428e016f3df8281--ClashX.dmg
SHA256: 5ea6e66a16eb99a1c7e4309e046e97cfa76ef13e60de019941ed427d49362590
```

**Comment by goalidea** [comment]
ok! Maybe it's my network problem
```
% brew fetch clashx-pro 
==> Downloading https://appcenter.vercel.app/clashx/clashx-pro/1.96.1.1
-=O=-               #    #     #     #                                        
curl: (7) Failed to connect to appcenter.vercel.app port 443: Operation timed out
Error: Download failed on Cask 'clashx-pro' with message: Download failed: https://appcenter.vercel.app/clashx/clashx-pro/1.96.1.1
```

**Pull request merged**
