### PR TITLE
Update microsoft-edge-dev from 77.0.235.5 to 78.0.244.0

### PR DESCRIPTION
**Pull request by faradaytrs**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Please rebase, the CI error should be fixed by https://github.com/Homebrew/homebrew-cask/pull/67588.

**Comment by faradaytrs** [comment]
@reitermarkus now build fails with 
```
Error: Some packages are still installed, add them to uninstall pkgutil:
com.microsoft.package.Microsoft_AutoUpdate.app
Error: Some launch jobs are still installed, add them to uninstall launchctl:
com.microsoft.autoupdate.helper
com.microsoft.update.agent
Error: Some launch jobs were not unloaded, add them to uninstall launchctl:
com.microsoft.autoupdate.helper
com.microsoft.update.agent
Error: Build failed.
```

**Comment by reitermarkus** [comment]
Yes, please add all of them to `zap` instead of `uninstall`.

**Comment by coreygo** [comment]
Added `brew cask zap microsoft-edge-dev` in #7777.

**Pull request closed without merging**
