### PR TITLE
Update microsoft-edge-canary

### PR DESCRIPTION
**Pull request by coreygo**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by coreygo** [comment]
Update in response to @vitorgalvao, https://github.com/Homebrew/homebrew-cask-versions/issues/7778#issuecomment-526716413

**Comment by vitorgalvao** [comment]
Thank you!

**Comment by coreygo** [comment]
@vitorgalvao Microsoft changed the package names from `com.microsoft.Edge` to `com.microsoft.edgemac`. I've updated `microsoft-edge-dev` in #7827. Will monitor and update `microsoft-edge-beta` as Microsoft has probably updated that package name in the next build.

**Comment by coreygo** [comment]
<details><summary>`brew cask zap microsoft-edge-canary` does work locally and addresses this…</summary>
<p>

```sh
==> Uninstalling Cask microsoft-edge-canary
==> Uninstalling packages:
com.microsoft.edgemac.Canary
==> Purging files for version latest of Cask microsoft-edge-canary
Error: Some packages are still installed, add them to uninstall pkgutil:
com.microsoft.package.Microsoft_AutoUpdate.app
Error: Some launch jobs are still installed, add them to uninstall launchctl:
com.microsoft.autoupdate.helper
com.microsoft.update.agent
Error: Some launch jobs were not unloaded, add them to uninstall launchctl:
com.microsoft.autoupdate.helper
com.microsoft.update.agent
Error: Build failed.
```

</p>
</details>

**Pull request merged**
