### PR TITLE
Update openzfs-dev from 2.1.6rc7 to 2.1.99

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.
---
`livecheck` is broken because announcement topic name on forum has unusual format. Please label with `help wanted`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
If upstream and changing the formatting of the dev builds that are listed on the forum then `livecheck` will be almost impossible here. Previously there was consistency in the formatting of the forum posts and download links. There's also no indication  in the updated filenames that they are for the development environment, so it is hard to detect.

**Comment by bevanjkay** [comment]
Based on the popularity of this cask I don't think it is worth going to great lengths to try to support a livecheck here...

openzfs-dev
30 days: n/a
90 days: 2 (#5244)
365 days: 5 (#7191)
Age: 860 days (added 2020, December 24)

**Comment by yurikoles** [comment]
> Based on the popularity of this cask I don't think it is worth going to great lengths to try to support a livecheck here...
> 
> ```
> openzfs-dev
> 30 days: n/a
> 90 days: 2 (#5244)
> 365 days: 5 (#7191)
> Age: 860 days (added 2020, December 24)
> ```

Oh, It seems like it's only my installs on different Macs and macOS instances. Let's completely drop this cask instead?

**Comment by bevanjkay** [comment]
@yurikoles Sounds good. If you still plan to use the cask you can drop it in a personal tap :)

**Comment by yurikoles** [comment]
Could you please provide me a way to get these numbers? I don't see any statistics for this repo's casks from `brew info`.

**Comment by bevanjkay** [comment]
I use the `cask-analytics` script from here - https://github.com/vitorgalvao/tiny-scripts

**Pull request closed without merging**
