### PR TITLE
Ableton Live Suite11

### PR DESCRIPTION
**Pull request by SloBloLabs**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @SloBloLabs.

**Review by miccal — APPROVED** [review]

**Comment by FlavioB79** [comment]
So I'm wondering how to install Ableton Live Suite 11 as brew is not showing me the *11 versions to be available:
brew search ableton
==> Formulae
lepton

==> Casks
ableton-live-intro         ableton-live-standard      lepton
ableton-live-lite          ableton-live-suite

Thanks for your help.
F.

**Comment by bevanjkay** [comment]
Run `brew tap homebrew/cask-versions`

**Comment by FlavioB79** [comment]
Thanks!
F.

https://www.instagram.com/boniforti_music
https://soundcloud.com/boniforti_music
https://bonny-j.bandcamp.com


Am Sa., 23. März 2024 um 11:12 Uhr schrieb Bevan Kay <
***@***.***>:

**Pull request merged**
