### PR TITLE
Update obs-beta from 28.0.0-rc2 to 28.1.0-rc1

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by samford — COMMENTED** [review]
I pushed a commit that fixes the `livecheck` block. In this case, we can simply identify the version from the tag (i.e., matching against the filename wasn't necessary). Since this cask targets unstable versions, I added the `prerelease:true` query to the URL to avoid stable releases.

**Review by samford — APPROVED** [review]

**Comment by bevanjkay** [comment]
@samford I am wondering if this is an instance where the cask should update to a newer stable version rather than be locked to the latest `pre-release` version, as the stable cask is currently on a later version than the beta cask. 

My thinking is that on apps that `conflict_with` the main cask, the beta should generally update to the latest available version unless there is a specific branch tracking mechanism upstream.

Because `obs-beta` and `obs` cannot be installed at the same time, I don't see why `obs-beta` should only receive the release candidate, where the `obs` cask will receive the final release. Especially considering not every version receives a `beta` or `rc`. For example https://github.com/obsproject/obs-studio/releases/tag/28.1.2

**Comment by p-linnane** [comment]
@bevanjkay You have swayed me on this issue. I think that the `beta` casks should update to whatever the latest version is whether beta or stable. I'm going to take this approach while working through https://github.com/Homebrew/homebrew-cask-versions/issues/14993.

**Comment by bevanjkay** [comment]
@p-linnane The challenge is that sometimes the upstream methodology differs. Some update to beta/rc only and some will update to the latest regardless of branch. 

Example: `hyper-canary` is locked to pre-releases only upstream (when using their in-app updating) even when there is a newer stable build. `propresenter-beta` gets bumped when there's a new stable release. 

Our challenge is working out which approach suits when upstream are silent on the matter.

My preference (as previously stated) is that when you can only choose to install the beta OR the stable cask that it should always grab the latest. But when the beta and stable cask can be installed separately this could be considered differently (app is named differently for the branch).

**Comment by p-linnane** [comment]
I touched on this in Slack utilizing `brave-browser-beta`, `brave-browser-dev`, and `brave-browser-nightly` as examples. I think that if there are dedicated channels, it should stay on those. For things that come all in one channel, I think we should use the methodology of absolute latest. What do you think?

**Comment by samford** [comment]
@bevanjkay I agree that allowing certain unstable casks to update to a stable version (when available) makes sense in the context you described. I mentioned something similar in the past but with fewer details, so I appreciate your rationale. I'll open a PR to loosen this `livecheck` block.

**Pull request merged**
