### PR TITLE
utm-beta: revert to 4.4.2

### PR DESCRIPTION
**Pull request by chenrui333**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

image

image

### CODE REVIEW

**Comment by p-linnane** [comment]
So this is kind of weird. We usually keep these `beta` casks on the absolute latest version, whether it's beta or stable. It's kind of confusing, but it becomes very complex to only do the unstable releases sometimes.

**Comment by bevanjkay** [comment]
@p-linnane I think it was likely intentional at the time, https://github.com/Homebrew/homebrew-cask-versions/pull/14917#issuecomment-1287123638
But it's probably better that moving forward this isn't restricted to `prereleases` and targets whichever the bleeding-edge release (be it stable or pre-release).

**Comment by p-linnane** [comment]
Ah right. I misunderstood. Agreed that these should be whatever bleeding-edge is.

**Comment by bevanjkay** [comment]
Didn't mean to close this 🤦‍♂️

**Pull request closed without merging**
