### PR TITLE
Update brave-browser-beta from 85.1.14.78,114.78 to 85.1.15.46,115.46

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by miccal** [comment]
A rebase should fix the test failure:
```
audit for transmission-nightly: failed
 - exception while auditing transmission-nightly: 502 Bad Gateway
##[error]exception while auditing transmission-nightly: 502 Bad Gateway
```

**Comment by LanikSJ** [comment]
#9605 passed no problem it seems not sure what happen here.

**Comment by miccal** [comment]
> #9605 passed no problem it seems not sure what happen here.

Just a temporary issue with `transmission-nightly`'s `url`'s.

**Comment by reitermarkus** [comment]
Already merged now in https://github.com/Homebrew/homebrew-cask-versions/pull/9605.

**Pull request closed without merging**
