### PR TITLE
Add Oracle JDK 8 update 202

### PR DESCRIPTION
**Pull request by Enrico204**
Added Oracle JDK 8 (update 202).

Note that `java8` is broken now, so maybe it should be removed. However, I named this `oracle-jdk8` because `java8` was under the name "OpenJDK" and instead is the "Oracle distribution of Java 8". Unfortunately, JDK 8 is not available anymore (see https://jdk.java.net/8/ and issue https://github.com/Homebrew/homebrew-cask/issues/58311 )

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-versions/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by reitermarkus** [comment]
Since the `java8` cask is broken and this is the only version left (according to 
https://github.com/Homebrew/homebrew-cask/issues/58311#issuecomment-460011677), this should probably replace `java8` instead.

**Comment by Enrico204** [comment]
Shall I modify this PR or create a new one?

**Comment by reitermarkus** [comment]
@Enrico204, whatever is easier for you.

**Comment by msdos** [comment]
I just did a `brew cask edit java8` and pasted the file presented in https://github.com/Homebrew/homebrew-cask-versions/pull/6934/commits/75334737c961a4c16e9889ef5bb67a65fa6eee4b. It works. Thanks for this fix.

**Pull request merged**
