### PR TITLE
Update utm-beta from 4.0.7 to 4.0.8

### PR DESCRIPTION
**Pull request by rogeriopradoj**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
This is pulling the latest GitHub tag, which is now the stable release. Merging this would put the beta version to the same version as stable.

@samford Is there an intelligent way for us to differentiate the beta releases since https://github.com/Homebrew/brew/issues/13853 has messed up our `:page_match` strategy?

**Comment by samford** [comment]
> Is there an intelligent way for us to differentiate the beta releases since [Homebrew/brew#13853](https://github.com/Homebrew/brew/issues/13853) has messed up our `:page_match` strategy?

Unfortunately, there's a fair amount of ambiguity around how versions are handled in unstable casks like this, so we need to answer some questions before we can create a proper check. For example:

* This is called `utm-beta`: Should it only use beta releases (latest beta is 4.0.5) or is it just any unstable version (e.g., 4.0.6 is RC, 4.0.7 is RC2)? I've seen other casks with a name like `*-beta` that also end up using alpha, RC, etc. releases at times.
* Should this be updated to stable releases when they're available (e.g., beta -> RC -> stable -> beta -> etc.) or should it only use unstable releases (e.g., beta -> RC -> beta -> etc.)? I feel like I've seen examples of both over time but I would have to dig to find them (i.e., I don't know any off the top of my head).

If we can come to a conclusion on how versions should be handled for this cask, I can try to come up with a `livecheck` block but it may not be pretty (i.e., unstable releases use the same tag format as stable releases but at least they're marked as pre-release). That said, we don't have to obtain version information from the filename, so this isn't affected by the recent changes in the release HTML (in relation to assets list HTML).

**Comment by p-linnane** [comment]
Probably part of [a larger conversation](https://github.com/Homebrew/homebrew-cask/issues/112102) that was brought up, but hasn't seen much activity in the last year. My opinion is having the cask in `cask-versions` be the latest unstable build regardless of what it's called unless it has dedicated channels like `beta`, `dev`, `canary/nightly`.

**Comment by p-linnane** [comment]
New `livecheck` strategy is working. Closing this out as `v4.0.7` is the latest prerelease.

**Pull request closed without merging**
