### PR TITLE
Add java11

### PR DESCRIPTION
**Pull request by Stargator**
Adding Java 11 to the repo

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-versions/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
The Oracle JDK was renamed from `java` to [`oracle-jdk`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/oracle-jdk.rb).

**Comment by Stargator** [comment]
@commitay Well, that wasn't clear when I was searching brew for java 11. It doesn't following the token reference used for java 6 (`java6`), java 8 (`java8`), and java 10 (`java10`)

Could I create a Pull Request to update those to the new token reference format?

**Comment by commitay** [comment]
The `oracle-jdk` Java isn't "free" so we switched `java` to the OpenJDK build. The `java*` tokens are correct because there isn't a different "official Oracle" build to switch them to.

Renaming them will break existing installs as we currently don't have support for migrating renamed casks.

**Comment by Stargator** [comment]
The `java*` tokens are Oracle builds, they download the builds from http://download.oracle.com/otn-pub/java/jdk

But fine, JDK 11 is available via Homebrew that's why I came here.

**Pull request closed without merging**
