### PR TITLE
Update safari technology preview to v127

### PR DESCRIPTION
**Pull request by Logicer16**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by Logicer16** [comment]
CI is running on 10.15?

**Comment by sankalp-khare** [comment]
I guess we can close this PR and move directly to version 127?

**Comment by Logicer16** [comment]
@sankalp-khare No need, I’ll just commit the new version to this pr. We’re still waiting on Homebrew/homebrew-cask#107667 though.

**Review by cho-m — APPROVED** [review]
At this point in time, I will just merge this as the failures are due to Homebrew's CI behavior and the meaningful tests (e.g. macos-11.0) passed.

The CI failure shouldn't block the update and should be fixed separately.

**Pull request merged**
