### PR TITLE
Update vivaldi-snapshot from 2.12.1873.3 to 3.3.2001.3

### PR DESCRIPTION
**Pull request by tohn**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by miccal** [comment]
The `appcast` is showing the `version` as `3.2.1967.41`?

**Comment by tohn** [comment]
> The `appcast` is showing the `version` as `3.2.1967.41`?

Yes, but that's the stable version. The snapshot version is 3.2.1967.38: https://vivaldi.com/blog/snapshots/vivaldi-3-2-rc-1-desktop/

**Comment by miccal** [comment]
Actually, the `appcast` for the snapshots should be:
```
appcast "https://update.vivaldi.com/update/1.0/snapshot/mac/appcast.xml"
```
which says the latest snapshot version is `3.2.1967.43`, and the `app` should also be
```
app "Vivaldi Snapshot.app"
```

**Comment by tohn** [comment]
> Actually, the `appcast` for the snapshots should be:
> 
> ```
> appcast "https://update.vivaldi.com/update/1.0/snapshot/mac/appcast.xml"
> ```
> 
> which says the latest snapshot version is `3.2.1967.43`, and the `app` should also be
> 
> ```
> app "Vivaldi Snapshot.app"
> ```

Thank you, you're absolutely right. Fixed in my last commit and updated to the latest snapshot 3.3.2001.3.

**Pull request merged**
