### PR TITLE
keyclu-edge 0.5

### PR DESCRIPTION
**Pull request by Anze**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@Anze Generally an app found in `homebrew-cask-versions` would have a stable version in `homebrew-cask`. Is this current version considered the most stable?

**Comment by Anze** [comment]
[@bevanjkay](https://github.com/bevanjkay) In sense "not crashing" - yes. In sense "final" - not yet.

**Comment by bevanjkay** [comment]
I think we'd be better suited to have this in `homebrew-cask` as the cask with the token `keyclu` and then we would add `keyclu-edge` if there are two branches in future - as presently this cask represents the latest and most stable version of `keyclu`.

**Comment by Anze** [comment]
[@bevanjkay](https://github.com/bevanjkay) Thank you. Made PR to main repo.

**Pull request closed without merging**
